/**
 * image-gen.js — text-to-image generation for the DECORATIVE ("B") card scene (owner's path B).
 *
 * The owner's decor style is generated by an image model (OpenAI gpt-image-1 by default) from the
 * Skyline scene prompt (automation/scene-prompts.js). This client turns a composed prompt into raw
 * image bytes; engine/card.js then composites Skyline's logo/price/slogan on top. The result is a
 * DECORATIVE backdrop only — the scenes are generic aspirational travel moods, never an AI-faked
 * photo of the specific real destination (that's the "A" real-photo card's job).
 *
 * OWNER-GATED: needs OPENAI_API_KEY (or IMAGE_API_KEY). Without it, resolveImageGen() returns null
 * and the card flow falls back to the code-drawn gradient decor — so nothing breaks before the key
 * is set. The transport is injectable (fetchImpl) so it is testable offline with no key and no call.
 *
 * Anthropic has no image model; this deliberately calls a non-Anthropic image API at the owner's
 * explicit request. Errors and any key are redacted; per-image token usage is logged (cost meter).
 */

const { redact } = require("../engine/publish");

const OPENAI_IMAGES = "https://api.openai.com/v1/images/generations";

/**
 * Generate one image from a prompt. Returns { buffer, contentType, usage }.
 * @param {string} prompt  the composed image prompt (see scene-prompts.composePrompt)
 * @param {object} opts    apiKey, model, size, quality, timeoutMs, fetchImpl, endpoint
 */
async function generateSceneImage(prompt, opts = {}) {
  const key = opts.apiKey || process.env.OPENAI_API_KEY || process.env.IMAGE_API_KEY;
  if (!key) throw new Error("image-gen needs OPENAI_API_KEY (owner-gated)");
  const model = opts.model || process.env.IMAGE_MODEL || "gpt-image-1";
  const size = opts.size || process.env.IMAGE_SIZE || "1024x1536"; // portrait ~2:3 (card is cover-fit to 4:5)
  const quality = opts.quality || process.env.IMAGE_QUALITY || "medium"; // low|medium|high|auto
  const timeoutMs = opts.timeoutMs || Number(process.env.IMAGE_TIMEOUT_MS) || 45000;
  const endpoint = opts.endpoint || process.env.IMAGE_API_URL || OPENAI_IMAGES;
  const fetchImpl = opts.fetchImpl || ((...a) => fetch(...a));

  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  let res;
  try {
    res = await fetchImpl(endpoint, {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({ model, prompt: String(prompt || "").slice(0, 30000), n: 1, size, quality }),
      signal: controller.signal,
    });
  } catch (e) {
    if (e && e.name === "AbortError") throw new Error(`image-gen timed out after ${timeoutMs}ms`);
    throw new Error(redact(String((e && e.message) || e)));
  } finally {
    clearTimeout(timer);
  }

  const json = await res.json().catch(() => ({}));
  if (!res.ok || (json && json.error)) {
    throw new Error(redact((json && json.error && json.error.message) || `HTTP ${res.status}`));
  }
  const b64 = json && json.data && json.data[0] && json.data[0].b64_json;
  if (!b64) throw new Error("image-gen: no image in response");
  const buffer = Buffer.from(b64, "base64");
  // Validate the returned bytes before we render/embed them (defense-in-depth: bound memory, and
  // reject a non-image payload so a bad response falls back to the gradient decor, never crashes).
  const MAX = Number(process.env.IMAGE_MAX_BYTES) || 20 * 1024 * 1024;
  if (buffer.length < 100 || buffer.length > MAX) throw new Error(`image-gen: image size ${buffer.length}B out of bounds`);
  const okMagic =
    (buffer[0] === 0x89 && buffer[1] === 0x50) || // png
    (buffer[0] === 0xff && buffer[1] === 0xd8) || // jpeg
    (buffer[0] === 0x47 && buffer[1] === 0x49) || // gif
    (buffer[0] === 0x52 && buffer[1] === 0x49);   // riff/webp
  if (!okMagic) throw new Error("image-gen: response is not a recognised image format");
  const usage = json.usage || null;
  // Cost meter: log per-image token usage (never the key/prompt).
  try { console.log(JSON.stringify({ evt: "image_gen", model, size, quality, bytes: buffer.length, usage })); } catch { /* ignore */ }
  return { buffer, contentType: "image/png", usage };
}

/** Return a generator fn if an image API key is configured, else null (→ gradient-decor fallback). */
function resolveImageGen(opts = {}) {
  const key = opts.apiKey || process.env.OPENAI_API_KEY || process.env.IMAGE_API_KEY;
  if (!key) return null;
  return (prompt, o = {}) => generateSceneImage(prompt, { ...opts, ...o });
}

module.exports = { generateSceneImage, resolveImageGen };
